# Direct mappings for events that don't follow standard patterns
PARIS_TO_OLD_DIRECT = {
    # Track events (distance conversions)
    "Men's 100m": "100 metres, Men",
    "Women's 100m": "100 metres, Women",
    "Men's 200m": "200 metres, Men",
    "Women's 200m": "200 metres, Women",
    "Men's 400m": "400 metres, Men",
    "Women's 400m": "400 metres, Women",
    "Men's 800m": "800 metres, Men",
    "Women's 800m": "800 metres, Women",
    "Men's 1500m": "1,500 metres, Men",
    "Women's 1500m": "1,500 metres, Women",
    "Men's 5000m": "5,000 metres, Men",
    "Women's 5000m": "5,000 metres, Women",
    "Men's 10,000m": "10,000 metres, Men",
    "Women's 10,000m": "10,000 metres, Women",
    "Men's 110m Hurdles": "110 metres Hurdles, Men",
    "Women's 100m Hurdles": "100 metres Hurdles, Women",
    "Men's 400m Hurdles": "400 metres Hurdles, Men",
    "Women's 400m Hurdles": "400 metres Hurdles, Women",
    "Men's 3000m Steeplechase": "3,000 metres Steeplechase, Men",
    "Women's 3000m Steeplechase": "3,000 metres Steeplechase, Women",
    "Men's Marathon": "Marathon, Men",
    "Women's Marathon": "Marathon, Women",
    "Men's 20km Race Walk": "20 kilometres Race Walk, Men",
    "Women's 20km Race Walk": "20 kilometres Race Walk, Women",
    "Marathon Race Walk Relay Mixed": "Relay, Mixed",

    # Relays
    "Men's 4 x 100m Relay": "4 × 100 metres Relay, Men",
    "Women's 4 x 100m Relay": "4 × 100 metres Relay, Women",
    "Men's 4 x 400m Relay": "4 × 400 metres Relay, Men",
    "Women's 4 x 400m Relay": "4 × 400 metres Relay, Women",
    "4 x 400m Relay Mixed": "4 × 400 metres Relay, Mixed",

    # Field events
    "Men's Long Jump": "Long Jump, Men",
    "Women's Long Jump": "Long Jump, Women",
    "Men's Triple Jump": "Triple Jump, Men",
    "Women's Triple Jump": "Triple Jump, Women",
    "Men's High Jump": "High Jump, Men",
    "Women's High Jump": "High Jump, Women",
    "Men's Pole Vault": "Pole Vault, Men",
    "Women's Pole Vault": "Pole Vault, Women",
    "Men's Shot Put": "Shot Put, Men",
    "Women's Shot Put": "Shot Put, Women",
    "Men's Discus Throw": "Discus Throw, Men",
    "Women's Discus Throw": "Discus Throw, Women",
    "Men's Javelin Throw": "Javelin Throw, Men",
    "Women's Javelin Throw": "Javelin Throw, Women",
    "Men's Hammer Throw": "Hammer Throw, Men",
    "Women's Hammer Throw": "Hammer Throw, Women",
    "Men's Decathlon": "Decathlon, Men",
    "Women's Heptathlon": "Heptathlon, Women",

    # Swimming
    "Men's 50m Freestyle": "50 metres Freestyle, Men",
    "Women's 50m Freestyle": "50 metres Freestyle, Women",
    "Men's 100m Freestyle": "100 metres Freestyle, Men",
    "Women's 100m Freestyle": "100 metres Freestyle, Women",
    "Men's 200m Freestyle": "200 metres Freestyle, Men",
    "Women's 200m Freestyle": "200 metres Freestyle, Women",
    "Men's 400m Freestyle": "400 metres Freestyle, Men",
    "Women's 400m Freestyle": "400 metres Freestyle, Women",
    "Men's 800m Freestyle": "800 metres Freestyle, Men",
    "Women's 800m Freestyle": "800 metres Freestyle, Women",
    "Men's 1500m Freestyle": "1,500 metres Freestyle, Men",
    "Women's 1500m Freestyle": "1,500 metres Freestyle, Women",
    "Men's 100m Backstroke": "100 metres Backstroke, Men",
    "Women's 100m Backstroke": "100 metres Backstroke, Women",
    "Men's 200m Backstroke": "200 metres Backstroke, Men",
    "Women's 200m Backstroke": "200 metres Backstroke, Women",
    "Men's 100m Breaststroke": "100 metres Breaststroke, Men",
    "Women's 100m Breaststroke": "100 metres Breaststroke, Women",
    "Men's 200m Breaststroke": "200 metres Breaststroke, Men",
    "Women's 200m Breaststroke": "200 metres Breaststroke, Women",
    "Men's 100m Butterfly": "100 metres Butterfly, Men",
    "Women's 100m Butterfly": "100 metres Butterfly, Women",
    "Men's 200m Butterfly": "200 metres Butterfly, Men",
    "Women's 200m Butterfly": "200 metres Butterfly, Women",
    "Men's 200m Individual Medley": "200 metres Individual Medley, Men",
    "Women's 200m Individual Medley": "200 metres Individual Medley, Women",
    "Men's 400m Individual Medley": "400 metres Individual Medley, Men",
    "Women's 400m Individual Medley": "400 metres Individual Medley, Women",
    "Men's 4 x 100m Freestyle Relay": "4 × 100 metres Freestyle Relay, Men",
    "Women's 4 x 100m Freestyle Relay": "4 × 100 metres Freestyle Relay, Women",
    "Men's 4 x 200m Freestyle Relay": "4 × 200 metres Freestyle Relay, Men",
    "Women's 4 x 200m Freestyle Relay": "4 × 200 metres Freestyle Relay, Women",
    "Men's 4 x 100m Medley Relay": "4 × 100 metres Medley Relay, Men",
    "Women's 4 x 100m Medley Relay": "4 × 100 metres Medley Relay, Women",
    "Mixed 4 x 100m Medley Relay": "4 × 100 metres Medley Relay, Mixed",
    "Men's 10km": "10 kilometres Open Water, Men",
    "Women's 10km": "10 kilometres Open Water, Women",

    # Diving
    "Men's 3m Springboard": "Springboard, Men",
    "Women's 3m Springboard": "Springboard, Women",
    "Men's 10m Platform": "Platform, Men",
    "Women's 10m Platform": "Platform, Women",
    "Men's Synchronised 3m Springboard": "Synchronized Springboard, Men",
    "Women's Synchronised 3m Springboard": "Synchronized Springboard, Women",
    "Men's Synchronised 10m Platform": "Synchronized Platform, Men",
    "Women's Synchronised 10m Platform": "Synchronized Platform, Women",

    # Artistic Gymnastics
    "Men's All-Around": "Individual All-Around, Men",
    "Women's All-Around": "Individual All-Around, Women",
    "Men's Floor Exercise": "Floor Exercise, Men",
    "Women's Floor Exercise": "Floor Exercise, Women",
    "Men's Pommel Horse": "Pommelled Horse, Men",
    "Men's Rings": "Rings, Men",
    "Men's Vault": "Horse Vault, Men",
    "Women's Vault": "Horse Vault, Women",
    "Men's Parallel Bars": "Parallel Bars, Men",
    "Men's Horizontal Bar": "Horizontal Bar, Men",
    "Women's Uneven Bars": "Uneven Bars, Women",
    "Women's Balance Beam": "Balance Beam, Women",
    "Men's Team": "Team, Men",
    "Women's Team": "Team, Women",

    # Rhythmic Gymnastics
    "Individual All-Around": "Individual All-Around, Women",
    "Group All-Around": "Group, Women",

    # Artistic Swimming
    "Duet": "Duet, Women",
    "Team": "Team, Women",

    # Fencing
    "Men's Foil Individual": "Foil, Individual, Men",
    "Women's Foil Individual": "Foil, Individual, Women",
    "Men's Épée Individual": "Épée, Individual, Men",
    "Women's Épée Individual": "Épée, Individual, Women",
    "Men's Sabre Individual": "Sabre, Individual, Men",
    "Women's Sabre Individual": "Sabre, Individual, Women",
    "Men's Foil Team": "Foil, Team, Men",
    "Women's Foil Team": "Foil, Team, Women",
    "Men's Épée Team": "Épée, Team, Men",
    "Women's Épée Team": "Épée, Team, Women",
    "Men's Sabre Team": "Sabre, Team, Men",
    "Women's Sabre Team": "Sabre, Team, Women",

    # Judo (weight classes)
    "Men -60 kg": "Extra-Lightweight, Men",
    "Men -66 kg": "Half-Lightweight, Men",
    "Men -73 kg": "Lightweight, Men",
    "Men -81 kg": "Half-Middleweight, Men",
    "Men -90 kg": "Middleweight, Men",
    "Men -100 kg": "Half-Heavyweight, Men",
    "Men +100 kg": "Heavyweight, Men",
    "Women -48 kg": "Extra-Lightweight, Women",
    "Women -52 kg": "Half-Lightweight, Women",
    "Women -57 kg": "Lightweight, Women",
    "Women -63 kg": "Half-Middleweight, Women",
    "Women -70 kg": "Middleweight, Women",
    "Women -78 kg": "Half-Heavyweight, Women",
    "Women +78 kg": "Heavyweight, Women",
    "Mixed Team": "Team, Mixed",

    # Taekwondo
    "Men -58kg": "Flyweight, Men",
    "Men -68kg": "Featherweight, Men",
    "Men -80kg": "Welterweight, Men",
    "Men +80kg": "Heavyweight, Men",
    "Women -49kg": "Flyweight, Women",
    "Women -57kg": "Featherweight, Women",
    "Women -67kg": "Welterweight, Women",
    "Women +67kg": "Heavyweight, Women",

    # Boxing
    "Men's 51kg": "Flyweight, Men",
    "Men's 57kg": "Featherweight, Men",
    "Men's 63.5kg": "Lightweight, Men",
    "Men's 71kg": "Light-Welterweight, Men",
    "Men's 80kg": "Middleweight, Men",
    "Men's 92kg": "Light-Heavyweight, Men",
    "Men's +92kg": "Super-Heavyweight, Men",
    "Women's 50kg": "Flyweight, Women",
    "Women's 54kg": "Bantamweight, Women",
    "Women's 57kg": "Featherweight, Women",
    "Women's 60kg": "Lightweight, Women",
    "Women's 66kg": "Welterweight, Women",
    "Women's 75kg": "Middleweight, Women",

    # Weightlifting
    "Men's 61kg": "Finweight, Men",
    "Men's 73kg": "Lightweight, Men",
    "Men's 89kg": "Middleweight, Men",
    "Men's 102kg": "Heavyweight I, Men",
    "Men's +102kg": "Super-Heavyweight, Men",
    "Women's 49kg": "Finweight, Women",
    "Women's 59kg": "Lightweight, Women",
    "Women's 71kg": "Middleweight, Women",
    "Women's 81kg": "Heavyweight, Women",
    "Women's +81kg": "Super-Heavyweight, Women",

    # Wrestling (Greco-Roman)
    "Men's Greco-Roman 60kg": "Flyweight, Greco-Roman, Men",
    "Men's Greco-Roman 67kg": "Bantamweight, Greco-Roman, Men",
    "Men's Greco-Roman 77kg": "Featherweight, Greco-Roman, Men",
    "Men's Greco-Roman 87kg": "Lightweight, Greco-Roman, Men",
    "Men's Greco-Roman 97kg": "Middleweight, Greco-Roman, Men",
    "Men's Greco-Roman 130kg": "Super-Heavyweight, Greco-Roman, Men",

    # Wrestling (Freestyle)
    "Men's Freestyle 57kg": "Flyweight, Freestyle, Men",
    "Men's Freestyle 65kg": "Bantamweight, Freestyle, Men",
    "Men's Freestyle 74kg": "Featherweight, Freestyle, Men",
    "Men's Freestyle 86kg": "Lightweight, Freestyle, Men",
    "Men's Freestyle 97kg": "Middleweight, Freestyle, Men",
    "Men's Freestyle 125kg": "Super-Heavyweight, Freestyle, Men",
    "Women's Freestyle 50kg": "Flyweight, Freestyle, Women",
    "Women's Freestyle 53kg": "Bantamweight, Freestyle, Women",
    "Women's Freestyle 57kg": "Featherweight, Freestyle, Women",
    "Women's Freestyle 62kg": "Lightweight, Freestyle, Women",
    "Women's Freestyle 68kg": "Middleweight, Freestyle, Women",
    "Women's Freestyle 76kg": "Heavyweight, Freestyle, Women",

    # Cycling - Road
    "Men's Road Race": "Road Race, Individual, Men",
    "Women's Road Race": "Road Race, Individual, Women",
    "Men's Individual Time Trial": "Individual Time Trial, Men",
    "Women's Individual Time Trial": "Individual Time Trial, Women",

    # Cycling - Track
    "Men's Sprint": "Sprint, Men",
    "Women's Sprint": "Sprint, Women",
    "Men's Keirin": "Keirin, Men",
    "Women's Keirin": "Keirin, Women",
    "Men's Omnium": "Omnium, Men",
    "Women's Omnium": "Omnium, Women",
    "Men's Team Sprint": "Team Sprint, Men",
    "Women's Team Sprint": "Team Sprint, Women",
    "Men's Team Pursuit": "Team Pursuit, 4,000 metres, Men",
    "Women's Team Pursuit": "Team Pursuit (6 laps), Women",
    "Men's Madison": "Madison, Men",
    "Women's Madison": "Madison, Women",

    # Cycling - BMX
    "Men's BMX Racing": "BMX, Men",
    "Women's BMX Racing": "BMX, Women",

    # Cycling - Mountain Bike
    "Men's Cross-country": "Cross-Country, Men",
    "Women's Cross-country": "Cross-Country, Women",

    # Canoe Sprint
    "Men's Kayak Single 1000m": "Kayak Singles, 1,000 metres, Men",
    "Men's Kayak Single": "Kayak Singles, Slalom, Men",
    "Women's Kayak Single 500m": "Kayak Singles, 500 metres, Women",
    "Women's Kayak Single": "Kayak Singles, Slalom, Women",
    "Men's Canoe Single 1000m": "Canadian Singles, 1,000 metres, Men",
    "Men's Canoe Single": "Canadian Singles, Slalom, Men",
    "Women's Canoe Single 200m": "Canadian Singles, 200 metres, Women",
    "Women's Canoe Single": "Canadian Singles, Slalom, Women",
    "Men's Kayak Double 500m": "Kayak Doubles, 500 metres, Men",
    "Women's Kayak Double 500m": "Kayak Doubles, 500 metres, Women",
    "Men's Canoe Double 500m": "Canadian Doubles, 500 metres, Men",
    "Women's Canoe Double 500m": "Canadian Doubles, 500 metres, Women",
    "Men's Kayak Four 500m": "Kayak Fours, 500 metres, Men",
    "Women's Kayak Four 500m": "Kayak Fours, 500 metres, Women",
    "Men's Kayak Cross": "Kayak Singles, Slalom, Men",
    "Women's Kayak Cross": "Kayak Singles, Slalom, Women",

    # Rowing
    "Men's Single Sculls": "Single Sculls, Men",
    "Women's Single Sculls": "Single Sculls, Women",
    "Men's Double Sculls": "Double Sculls, Men",
    "Women's Double Sculls": "Double Sculls, Women",
    "Men's Quadruple Sculls": "Quadruple Sculls, Men",
    "Women's Quadruple Sculls": "Quadruple Sculls, Women",
    "Lightweight Men's Double Sculls": "Lightweight Double Sculls, Men",
    "Lightweight Women's Double Sculls": "Lightweight Double Sculls, Women",
    "Men's Pair": "Coxless Pairs, Men",
    "Women's Pair": "Coxless Pairs, Women",
    "Men's Four": "Four, Men",
    "Women's Four": "Coxless Fours, Women",
    "Men's Eight": "Eights, Men",
    "Women's Eight": "Eights, Women",

    # Sailing
    "Men's Dinghy": "One Person Dinghy, Men",
    "Women's Dinghy": "One Person Dinghy, Women",
    "Men's Skiff": "Skiff, Men",
    "Women's Skiff": "Skiff, Women",
    "Men's Windsurfing": "Windsurfer, Men",
    "Women's Windsurfing": "Windsurfer, Women",
    "Men's Kite": "Windsurfer, Men",
    "Women's Kite": "Windsurfer, Women",
    "Mixed Dinghy": "Two Person Dinghy, Mixed",
    "Mixed Multihull": "Multihull, Mixed",

    # Shooting
    "10m Air Pistol Men": "Air Pistol, 10 metres, Men",
    "10m Air Pistol Women": "Air Pistol, 10 metres, Women",
    "10m Air Rifle Men": "Air Rifle, 10 metres, Men",
    "10m Air Rifle Women": "Air Rifle, 10 metres, Women",
    "25m Pistol Women": "Sporting Pistol, 25 metres, Women",
    "25m Rapid Fire Pistol Men": "Rapid-Fire Pistol, 25 metres, Men",
    "50m Rifle 3 Positions Men": "Small-Bore Rifle, Three Positions, 50 metres, Men",
    "50m Rifle 3 Positions Women": "Small-Bore Rifle, Three Positions, 50 metres, Women",
    "Trap Men": "Trap, Men",
    "Trap Women": "Trap, Women",
    "Skeet Men": "Skeet, Men",
    "Skeet Women": "Skeet, Women",
    "10m Air Rifle Mixed Team": "Air Rifle, 10 metres, Team, Mixed",
    "10m Air Pistol Mixed Team": "Air Pistol, 10 metres, Team, Mixed",
    "Skeet Mixed Team": "Trap, Team, Mixed",

    # Table Tennis
    "Men's Singles": "Singles, Men",
    "Women's Singles": "Singles, Women",
    "Men's Doubles": "Doubles, Men",
    "Women's Doubles": "Doubles, Women",
    "Mixed Doubles": "Doubles, Mixed",

    # Tennis
    "Men's Singles": "Singles, Men",
    "Women's Singles": "Singles, Women",
    "Men's Doubles": "Doubles, Men",
    "Women's Doubles": "Doubles, Women",
    "Mixed Doubles": "Doubles, Mixed",

    # Badminton
    "Men's Singles": "Singles, Men",
    "Women's Singles": "Singles, Women",
    "Men's Doubles": "Doubles, Men",
    "Women's Doubles": "Doubles, Women",
    "Mixed Doubles": "Doubles, Mixed",

    # Equestrian
    "Dressage Individual": "Individual, Open",
    "Dressage Team": "Dressage, Team",
    "Eventing Individual": "Eventing, Individual",
    "Eventing Team": "Eventing, Team",
    "Jumping Individual": "Jumping, Individual",
    "Jumping Team": "Jumping, Team",

    # Golf
    "Men's Individual Stroke Play": "Individual, Men",
    "Women's Individual Stroke Play": "Individual, Women",

    # Triathlon
    # NOTE: Generic "Men", "Women" entries removed to avoid conflicts with team sports like Football, Basketball
    # These are now handled by the discipline-aware conversion logic in convert_paris_event_to_old()
    "Mixed Relay": "Team Relay, Mixed",

    # Generic Individual events (used by Archery, Modern Pentathlon, Triathlon)
    # Note: Triathlon historically uses "Olympic Distance" but Archery/Modern Pentathlon use "Individual"
    # Mapping to "Individual" as it matches 2 of 3 sports; Triathlon context is handled separately
    "Men's Individual": "Individual, Men",
    "Women's Individual": "Individual, Women",

    # Skateboarding
    "Men's Street": "Street, Men",
    "Women's Street": "Street, Women",
    "Men's Park": "Park, Men",
    "Women's Park": "Park, Women",

    # Sport Climbing
    "Men's Boulder & Lead": "Individual, Men",
    "Women's Boulder & Lead": "Individual, Women",
    "Men's Speed": "Individual, Men",
    "Women's Speed": "Individual, Women",

    # Surfing
    "Men's Shortboard": "Shortboard, Men",
    "Women's Shortboard": "Shortboard, Women",

    # Breaking
    "B-Boys": "Individual, Men",
    "B-Girls": "Individual, Women",

    # Team sports (simple mappings)
    "Men's Basketball": "Basketball, Men",
    "Women's Basketball": "Basketball, Women",
    "Men's 3x3 Basketball": "3x3 Basketball, Men",
    "Women's 3x3 Basketball": "3x3 Basketball, Women",
    "Men's Beach Volleyball": "Beach Volleyball, Men",
    "Women's Beach Volleyball": "Beach Volleyball, Women",
    "Men's Volleyball": "Volleyball, Men",
    "Women's Volleyball": "Volleyball, Women",
    "Men's Football": "Football, Men",
    "Women's Football": "Football, Women",
    "Men's Handball": "Handball, Men",
    "Women's Handball": "Handball, Women",
    "Men's Hockey": "Hockey, Men",
    "Women's Hockey": "Hockey, Women",
    "Men's Rugby Sevens": "Rugby Sevens, Men",
    "Women's Rugby Sevens": "Rugby Sevens, Women",
    "Men's Water Polo": "Water Polo, Men",
    "Women's Water Polo": "Water Polo, Women",
}

# Set of all team sport events from olympic_athlete_event_results.csv
TEAM_SPORTS = {
    "0-½ Ton, Open",
    "1 mile, Team, Handicap, Men",
    "1,600 metres Medley Relay, Men",
    "1-2 Ton, Open",
    "10 metres, Open",
    "10-20 Ton, Open",
    "100 kilometres Team Time Trial, Men",
    "12 foot, Open",
    "12 metres, Open",
    "18 foot, Open",
    "2 × 6 kilometres and 2 × 7.5 kilometres Relay, Mixed",
    "2,000 metres Relay, Mixed",
    "2-3 Ton, Open",
    "20+ Ton, Open",
    "200 metres Team Swimming, Men",
    "26th Federal Festival, Society and Association Contests, Non-Simultaneous, Shooting Championships, Honorary Members and Associates, Men",
    "26th Federal Festival, Society and Association Contests, Non-Simultaneous, Shooting Championships, Honorary Members and Associates, Women",
    "26th Federal Festival, Society and Association Contests, Non-Simultaneous, Shooting Championships, Youth, Men",
    "3 miles, Team, Men",
    "3 × 5 kilometres Relay, Women",
    "3 × 7.5 kilometres Relay, Women",
    "3,000 metres Relay, Women",
    "3,000 metres, Team, Men",
    "3-10 Ton, Open",
    "30 metres², Open",
    "3x3 Basketball, Men",
    "3x3 Basketball, Women",
    "4 miles, Team, Men",
    "4 × 10 kilometres Relay, Men",
    "4 × 100 metres Freestyle Relay, Men",
    "4 × 100 metres Freestyle Relay, Women",
    "4 × 100 metres Medley Relay, Men",
    "4 × 100 metres Medley Relay, Mixed",
    "4 × 100 metres Medley Relay, Women",
    "4 × 100 metres Relay, Men",
    "4 × 100 metres Relay, Women",
    "4 × 200 metres Freestyle Relay, Men",
    "4 × 200 metres Freestyle Relay, Women",
    "4 × 400 metres Relay, Men",
    "4 × 400 metres Relay, Mixed",
    "4 × 400 metres Relay, Women",
    "4 × 440 yards Relay, Boys",
    "4 × 5 kilometres Relay, Women",
    "4 × 50 yards Freestyle Relay, Men",
    "4 × 6 kilometres Relay, Women",
    "4 × 7.5 kilometres Relay, Men",
    "4 × 7.5 kilometres Relay, Women",
    "40 metres², Open",
    "440 yards, Men",
    "5 kilometres, B1, Men",
    "5 kilometres, B1, Women",
    "5,000 metres Relay, Men",
    "5,000 metres, Team, Men",
    "5.5 metres, Open",
    "6 metres, Open",
    "6.5 metres, Open",
    "7 metres, Open",
    "8 metres, Open",
    "A-Class (Open), Open",
    "Air Pistol, 10 metres, Team, Mixed",
    "Air Rifle, 10 metres, Team, Mixed",
    "Alpinism, Open",
    "American Football, Men",
    "Australian Rules Football, Men",
    "Australian Team Pursuit, Professionals, Men",
    "B-Class (Under 60 feet), Open",
    "Bandy, Men",
    "Baseball, Men",
    "Basketball, Men",
    "Basketball, Women",
    "Beach Volleyball, Men",
    "Beach Volleyball, Women",
    "Bicycle Polo, Men",
    "Blé, Triples, Men",
    "C-Class, Open",
    "Canadian Doubles, 1,000 metres, Men",
    "Canadian Doubles, 10,000 metres, Men",
    "Canadian Doubles, 500 metres, Men",
    "Canadian Doubles, 500 metres, Women",
    "Canadian Doubles, 800 metres, Men",
    "Canadian Doubles, Slalom, Men",
    "Canadian Fours, 800 metres, Men",
    "Cesta Punta, Doubles, Men",
    "Cesta Punta, Triples, Men",
    "Complementary Military Training, Men",
    "Coxed Fours, Inriggers, Men",
    "Coxed Fours, Men",
    "Coxed Fours, Outriggers, Men",
    "Coxed Fours, Women",
    "Coxed Pairs, Men",
    "Coxed Quadruple Sculls, Women",
    "Coxless Fours, Boys",
    "Coxless Fours, Intermediate, Men",
    "Coxless Fours, Men",
    "Coxless Fours, Outriggers, Men",
    "Coxless Fours, Women",
    "Coxless Pairs, Boys",
    "Coxless Pairs, Intermediate, Men",
    "Coxless Pairs, Men",
    "Coxless Pairs, Women",
    "Cricket, Men",
    "Cross-Country, Team, Men",
    "Curling, Men",
    "Curling, Women",
    "Double Sculls, Intermediate, Men",
    "Double Sculls, Men",
    "Double Sculls, Women",
    "Doubles, Covered Courts, Men",
    "Doubles, Covered Courts, Mixed",
    "Doubles, Handicap, Men",
    "Doubles, Handicap, Mixed",
    "Doubles, Men",
    "Doubles, Mixed",
    "Doubles, Open",
    "Doubles, Professionals, Handicap, Men",
    "Doubles, Women",
    "Dueling Pistol, 30 metres, Team, Men",
    "Duet, Women",
    "Eights, Boys",
    "Eights, Intermediate, Men",
    "Eights, Men",
    "Eights, Women",
    "Festival for Societies of the Seine, Instructors, Men",
    "Festival for Societies of the Seine, Swimming, Individual, Men",
    "Foil, Team, Men",
    "Foil, Team, Women",
    "Folding Kayak Doubles, 10,000 metres, Men",
    "Football, Men",
    "Football, Women",
    "Four, Men",
    "Four, Open",
    "Four/Five, Men",
    "Free Exercise, Group A, Men",
    "Free Exercise, Group B, Men",
    "Free Exercise, Group C, Men",
    "Free Pistol, 50 metres, Team, Men",
    "Free Pistol, 50 yards, Team, Men",
    "Free Rifle, 400, 600 and 800 metres, Team, Men",
    "Free Rifle, Three Positions, 300 metres, Team, Men",
    "French Skiffs, Coxed Pairs, Men",
    "French Skiffs, Coxless Fours, Men",
    "Frontenis, Doubles, Men",
    "Frontenis, Doubles, Women",
    "Greatest height achieved (#3), Open",
    "Group, Women",
    "Handball, Men",
    "Handball, Women",
    "Hockey, Men",
    "Hockey, Women",
    "Horizontal Bar, Teams, Men",
    "Ice Dancing, Mixed",
    "Ice Hockey Exhibition, Men",
    "Ice Hockey, Men",
    "Ice Hockey, Women",
    "Jeu de berges, Quartets, Men",
    "Jeu lyonnais, Quartets, Men",
    "Kaatsen, Men",
    "Kayak Doubles, 1,000 metres, Men",
    "Kayak Doubles, 10,000 metres, Men",
    "Kayak Doubles, 200 metres, Men",
    "Kayak Doubles, 500 metres, Men",
    "Kayak Doubles, 500 metres, Women",
    "Kayak Doubles, 800 metres, Men",
    "Kayak Fours, 1,000 metres, Men",
    "Kayak Fours, 500 metres, Men",
    "Kayak Fours, 500 metres, Women",
    "Kayak Fours, 800 metres, Men",
    "Kayak Relay, 4 × 500 metres, Men",
    "Korfball, Mixed",
    "Lacrosse, Men",
    "Large Hill, Team, Men",
    "Lightweight Coxless Fours, Men",
    "Lightweight Coxless Pairs, Mixed",
    "Lightweight Double Sculls, Men",
    "Lightweight Double Sculls, Women",
    "Longest distance travelled (#4), Second Degree, Open",
    "Longest time travelled (#1), Handicap, Open",
    "Longest time travelled (#2), Handicap, Open",
    "Longest time travelled (#4), Second Degree, Open",
    "Madison, Men",
    "Madison, Women",
    "Maneuvering, International, British Firefighters, Men",
    "Maneuvering, International, Professional Firefighters, Men",
    "Maneuvering, International, Volunteer Firefighters, Men",
    "Mano, Doubles, Men",
    "Mano, Singles, Men",
    "Mano, Triples, Men",
    "Military Pistol, Team, Men",
    "Military Rifle, 200, 400, 500 and 600 metres, Team, Men",
    "Military Rifle, 200/500/600/800/900/1,000 yards, Team, Men",
    "Military Rifle, Prone, 300 and 600 metres, Team, Men",
    "Military Rifle, Prone, 300 metres, Team, Men",
    "Military Rifle, Prone, 600 metres, Team, Men",
    "Military Rifle, Standing, 300 metres, Team, Men",
    "Military Ski Patrol, Men",
    "Mixed Doubles, Mixed",
    "Monobob, Women",
    "Multihull, Mixed",
    "Multihull, Open",
    "National Team Sprint, Professionals, Men",
    "Normal Hill, Team, Mixed",
    "Open, Open",
    "Overall, Men",
    "Pairs, Mixed",
    "Pala Corta, Doubles, Men",
    "Pala, Doubles, Men",
    "Paleta Cuero, Doubles, Men",
    "Paleta Goma, Doubles, Men",
    "Parallel Bars, Teams, Men",
    "Partie à enlever, Men",
    "Partie à terrer, Men",
    "Pesäpallo, Men",
    "Pole Archery, Large Birds, Team, Men",
    "Pole Archery, Small Birds, Team, Men",
    "Polo, Men",
    "Preparatory Military Training, Group A, Men",
    "Preparatory Military Training, Group B, Men",
    "Preparatory Military Training, Group C, Men",
    "Preparatory Military Training, Group D, Men",
    "Quadruple Sculls, Men",
    "Quadruple Sculls, Women",
    "Relay, Mixed",
    "Renshu, Open",
    "Retrieval by Hook, Men",
    "Road Race, Team, Men",
    "Roller Hockey, Men",
    "Rugby Sevens, Men",
    "Rugby Sevens, Women",
    "Rugby, Men",
    "Running Target, Double Shot, Team, Men",
    "Running Target, Single Shot, Team, Men",
    "Sabre, Team, Men",
    "Sabre, Team, Women",
    "Skiff, Men",
    "Skiff, Open",
    "Skiff, Women",
    "Smal-Bore Rifle, Standing, 50 metres, Team, Men",
    "Small-Bore Rifle, 50 and 100 yards, Team, Men",
    "Small-Bore Rifle, Disappearing Target, 25 metres, Team, Men",
    "Small-Bore Rifle, Prone, 50 metres, Team, Men",
    "Softball, Women",
    "Synchronized Platform, Men",
    "Synchronized Platform, Women",
    "Synchronized Springboard, Men",
    "Synchronized Springboard, Women",
    "Tandem Sprint, 2,000 metres, Men",
    "Tandem Sprint, Professionals, Men",
    "Target Archery, 28 metres, Team, Men",
    "Target Archery, 33 metres, Team, Men",
    "Target Archery, 50 metres, Team, Men",
    "Team Aerials, Mixed",
    "Team All-Around, Free System, Men",
    "Team All-Around, Men",
    "Team All-Around, Swedish System, Men",
    "Team All-Around, Women",
    "Team Cross, Mixed",
    "Team Portable Apparatus, Women",
    "Team Pursuit (6 laps), Women",
    "Team Pursuit (8 laps), Men",
    "Team Pursuit, 1,980 yards, Men",
    "Team Pursuit, 4,000 metres, Men",
    "Team Pursuit, Women",
    "Team Relay, Mixed",
    "Team Round, Men",
    "Team Round, Women",
    "Team Sprint, Men",
    "Team Sprint, Professionals, Men",
    "Team Sprint, Women",
    "Team, Men",
    "Team, Mixed",
    "Team, Open",
    "Team, Women",
    "Three Person Keelboat, Open",
    "Three Person Keelboat, Women",
    "Trap, Team, Men",
    "Trap, Team, Mixed",
    "Tug-Of-War, Men",
    "Two Person Dinghy, Men",
    "Two Person Dinghy, Open",
    "Two Person Dinghy, Women",
    "Two Person Heavyweight Dinghy, Open",
    "Two Person Keelboat, Men",
    "Two Person Keelboat, Open",
    "Two, Men",
    "Two, Women",
    "Two-Man Teams With Cesta, Men",
    "Two-Man Teams With Cesta, Professional, Men",
    "Volleyball, Men",
    "Volleyball, Women",
    "Water Polo, Men",
    "Water Polo, Women",
    "½-1 Ton, Open",
    "Épée, Team, Men",
    "Épée, Team, Women",
    "Dressage, Team",
    "Eventing, Team",
    "Jumping, Team",
    "Two Person Dinghy, Mixed",
}


def convert_paris_event_to_old(event_name: str, discipline: str = "") -> str:
    """
    Convert a Paris 2024 Olympic event name to the old historical format.

    Args:
        event_name: The event name from the Paris medallists.csv dataset
        discipline: The discipline/sport name (optional, used for disambiguation)

    Returns:
        The corresponding event name in the old format from olympic_athlete_event_results.csv,
        or the original name if no mapping exists.
    """
    # First try direct mapping with event name
    if event_name in PARIS_TO_OLD_DIRECT:
        return PARIS_TO_OLD_DIRECT[event_name]

    # For generic event names like "Men" or "Women", combine with discipline
    if discipline and event_name in ["Men", "Women", "Mixed"]:
        # Special case for Triathlon - use "Olympic Distance" format
        if discipline == "Triathlon":
            return f"Olympic Distance, {event_name}"

        # Try "{discipline}, {event}"
        combined = f"{discipline}, {event_name}"
        if combined in PARIS_TO_OLD_DIRECT.values():
            return combined

        # Try "Men's {discipline}" or "Women's {discipline}" pattern
        prefixed = f"{event_name}'s {discipline}"
        if prefixed in PARIS_TO_OLD_DIRECT:
            return PARIS_TO_OLD_DIRECT[prefixed]

    return event_name


def is_team_sport(event_name: str) -> bool:
    """
    Check if an event is a team sport based on the old format event name.

    Args:
        event_name: The event name in the old format (from olympic_athlete_event_results.csv)

    Returns:
        True if the event is a team sport, False otherwise.
    """
    return event_name in TEAM_SPORTS